project:
  type: website

website:
  title: "Profit Times"
  navbar:
    left:
      - text: Latest Headlines
        menu:
        - text: "Standing Rock: Protests Threaten Nation’s Bottom Line"
          href: articles/standing-rock-profits.qmd
        - text: "Standing Rock Violence Disrupts Profit Flow "
          href: articles/standing-rock-violence.qmd
      - text: About
        href: about.qmd
      - text: "Games"
        menu:
        - text: "Wordle"
          href: games/wordle.qmd
        - text: "Tic Tac Toe"
          href: games/tictactoe.qmd
        - text: "Click the Button" 
          href: games/clickthebutton.qmd

format:
  html:
    theme: cosmo
    toc: true
    css: /styles.css?v=2
    include-after-body: 
      - snippets/rotating-bar.html
      - snippets/navbar-stocks.html
    footer: |
      <p style="text-align:center; font-size:0.9em; color:#555;">
        © 2025 Profit Times. All satire intended.
      </p>
