project:
  type: website

website:
  title: "Profit Times"
  navbar:
    left:
      - text: Profit Times
        href: index.qmd
      - text: Latest Headlines
        href: articles/standing-rock.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    include-after-body: snippets/rotating-bar.html
    footer: |
      <p style="text-align:center; font-size:0.9em; color:#555;">
        Â© 2025 Profit Times. All satire intended.
      </p>
